// router.js

import { createWebHistory, createRouter } from 'vue-router';

const routes = [
    {
        path: '/dashboard',
        component: () => import('./Pages/Dashboard.vue'),
        name: 'dashboard',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin',
        component: () => import('./Pages/Admin/Admin.vue'),
        name: 'admin',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/analytics',
        component: () => import('./Pages/Admin/Analytics.vue'),
        name: 'analytics',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/fintech',
        component: () => import('./Pages/Admin/Fintech.vue'),
        name: 'fintech',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/calendar',
        component: () => import('./Pages/Admin/Calendar.vue'),
        name: 'calendar',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/campaigns',
        component: () => import('./Pages/Admin/Campaigns.vue'),
        name: 'campaigns',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/inbox',
        component: () => import('./Pages/Admin/Inbox.vue'),
        name: 'inbox',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/messages',
        component: () => import('./Pages/Admin/Messages.vue'),
        name: 'messages',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/signin',
        component: () => import('./Pages/Admin/Signin.vue'),
        name: 'signin',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/signup',
        component: () => import('./Pages/Admin/Signup.vue'),
        name: 'signup',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/reset-password',
        component: () => import('./Pages/Admin/ResetPassword.vue'),
        name: 'reset-password',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/onboarding-01',
        component: () => import('./Pages/Admin/Onboarding01.vue'),
        name: 'onboarding-01',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/onboarding-02',
        component: () => import('./Pages/Admin/Onboarding02.vue'),
        name: 'onboarding-02',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/onboarding-03',
        component: () => import('./Pages/Admin/Onboarding03.vue'),
        name: 'onboarding-03',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/onboarding-04',
        component: () => import('./Pages/Admin/Onboarding04.vue'),
        name: 'onboarding-04',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/customers',
        component: () => import('./Pages/ecommerce/Customers.vue'),
        name: 'customers',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/orders',
        component: () => import('./Pages/ecommerce/Orders.vue'),
        name: 'orders',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/invoices',
        component: () => import('./Pages/ecommerce/Invoices.vue'),
        name: 'invoices',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/shop',
        component: () => import('./Pages/ecommerce/Shop.vue'),
        name: 'shop',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/shop2',
        component: () => import('./Pages/ecommerce/Shop2.vue'),
        name: 'shop2',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/product',
        component: () => import('./Pages/ecommerce/Product.vue'),
        name: 'product',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/cart',
        component: () => import('./Pages/ecommerce/Cart.vue'),
        name: 'cart',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/cart-2',
        component: () => import('./Pages/ecommerce/Cart2.vue'),
        name: 'cart2',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/cart-3',
        component: () => import('./Pages/ecommerce/Cart3.vue'),
        name: 'cart3',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/ecommerce/pay',
        component: () => import('./Pages/ecommerce/Pay.vue'),
        name: 'pay',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/users-tabs',
        component: () => import('./Pages/community/UsersTabs.vue'),
        name: 'users-tabs',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/users-tiles',
        component: () => import('./Pages/community/UsersTiles.vue'),
        name: 'users-tiles',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/profile',
        component: () => import('./Pages/community/Profile.vue'),
        name: 'profile',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/feed',
        component: () => import('./Pages/community/Feed.vue'),
        name: 'feed',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/forum',
        component: () => import('./Pages/community/Forum.vue'),
        name: 'forum',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/forum-post',
        component: () => import('./Pages/community/ForumPost.vue'),
        name: 'forum-post',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/meetups',
        component: () => import('./Pages/community/Meetups.vue'),
        name: 'meetups',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/community/meetups-post',
        component: () => import('./Pages/community/MeetupsPost.vue'),
        name: 'meetups-post',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/finance/cards',
        component: () => import('./Pages/finance/CreditCards.vue'),
        name: 'cards',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/finance/transactions',
        component: () => import('./Pages/finance/Transactions.vue'),
        name: 'transactions',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/finance/transaction-details',
        component: () => import('./Pages/finance/TransactionDetails.vue'),
        name: 'transaction-details',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/job/job-listing',
        component: () => import('./Pages/job/JobListing.vue'),
        name: 'job-listing',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/job/job-post',
        component: () => import('./Pages/job/JobPost.vue'),
        name: 'job-post',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/job/company-profile',
        component: () => import('./Pages/job/CompanyProfile.vue'),
        name: 'company-profile',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/tasks/kanban',
        component: () => import('./Pages/tasks/TasksKanban.vue'),
        name: 'tasks-kanban',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/tasks/list',
        component: () => import('./Pages/tasks/TasksList.vue'),
        name: 'tasks-list',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/settings/account',
        component: () => import('./Pages/settings/Account.vue'),
        name: 'account',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/settings/notifications',
        component: () => import('./Pages/settings/Notifications.vue'),
        name: 'notifications',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/settings/apps',
        component: () => import('./Pages/settings/Apps.vue'),
        name: 'apps',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/settings/plans',
        component: () => import('./Pages/settings/Plans.vue'),
        name: 'plans',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/settings/billing',
        component: () => import('./Pages/settings/Billing.vue'),
        name: 'billing',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/settings/feedback',
        component: () => import('./Pages/settings/Feedback.vue'),
        name: 'feedback',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/utility/changelog',
        component: () => import('./Pages/utility/Changelog.vue'),
        name: 'changelog',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/utility/roadmap',
        component: () => import('./Pages/utility/Roadmap.vue'),
        name: 'roadmap',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/utility/faqs',
        component: () => import('./Pages/utility/Faqs.vue'),
        name: 'faqs',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/utility/empty-state',
        component: () => import('./Pages/utility/EmptyState.vue'),
        name: 'empty-state',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/utility/404',
        component: () => import('./Pages/utility/PageNotFound.vue'),
        name: 'page-not-found',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/utility/knowledge-base',
        component: () => import('./Pages/utility/KnowledgeBase.vue'),
        name: 'knowledge-base',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/button',
        component: () => import('./Pages/component/ButtonPage.vue'),
        name: 'button-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/form',
        component: () => import('./Pages/component/FormPage.vue'),
        name: 'form-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/dropdown',
        component: () => import('./Pages/component/DropdownPage.vue'),
        name: 'dropdown-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/alert',
        component: () => import('./Pages/component/AlertPage.vue'),
        name: 'alert-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/modal',
        component: () => import('./Pages/component/ModalPage.vue'),
        name: 'modal-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/pagination',
        component: () => import('./Pages/component/PaginationPage.vue'),
        name: 'pagination-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/tabs',
        component: () => import('./Pages/component/TabsPage.vue'),
        name: 'tabs-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/breadcrumb',
        component: () => import('./Pages/component/BreadcrumbPage.vue'),
        name: 'breadcrumb-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/badge',
        component: () => import('./Pages/component/BadgePage.vue'),
        name: 'badge-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/avatar',
        component: () => import('./Pages/component/AvatarPage.vue'),
        name: 'avatar-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/tooltip',
        component: () => import('./Pages/component/TooltipPage.vue'),
        name: 'tooltip-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/accordion',
        component: () => import('./Pages/component/AccordionPage.vue'),
        name: 'accordion-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/admin/component/icons',
        component: () => import('./Pages/component/IconsPage.vue'),
        name: 'icons-page',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/:pathMatch(.*)*',
        component: () => import('./Pages/utility/PageNotFound.vue'),
        name: 'page-not-found',
        meta: { middleware: ['auth', 'verified'] },
    },
    {
        path: '/logout',
        component: () => import('./Pages/Admin/LogoutComponent.vue'),
        name: 'logout',
        meta: { middleware: ['auth', 'verified'] },
    },
    // Добавьте другие маршруты здесь, если необходимо
];

const router = createRouter({
    history: createWebHistory(),
    routes,
});

export default router;
